version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "8080:8080"
    environment:
      - MLFLOW_ARTIFACT_ROOT=/ml_artifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --backend-store-uri /mlruns
      --default-artifact-root /ml_artifacts
    volumes:
      - mlruns:/mlruns
      - ml_artifacts:/ml_artifacts

  kedro-pipeline:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:8080
      - MLFLOW_ARTIFACT_ROOT=/ml_artifacts
      - FS_API_KEY=${FS_API_KEY}
      - FS_PROJECT_NAME=${FS_PROJECT_NAME}
      - KEDRO_ENV=docker
    volumes:
      - ./data:/home/kedro_docker/data
      - ./src:/home/kedro_docker/src
      - ./conf:/home/kedro_docker/conf
      #only internally on Docker
      - mlruns:/mlruns
      - ml_artifacts:/ml_artifacts
    depends_on:
      - mlflow-server
    command: >
      kedro run --env docker

volumes:
  mlruns:
  ml_artifacts:



# se apagar o container as runs e artifacts depois desaparecem?

# 🔒 Não, as runs e os artefactos não desaparecem quando apagas os containers — desde que uses volumes nomeados como estás a usar.

# docker volume ls
