channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.0.1
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - lz4==4.4.4
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==5.9.8
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
