channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.0.1
- pip:
  - mlflow==2.21.0
  - lz4==4.4.4
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.15.2
  - xgboost==2.1.4
name: mlflow-env
