
parameters_feature_selection:
  # xgb
  model_params_xgb:
    n_estimators: 50
    max_depth: 4
    learning_rate: 0.1
    random_state: 42
    n_jobs: -1
    use_label_encoder: False
    eval_metric: mlogloss



  # BORUTA
  model_params_boruta:
    n_estimators: 50
    max_depth: 4
    random_state: 42
    learning_rate: 0.1
    n_jobs: -1
  max_iter_boruta: 100


  # CHI2
  k_features_chi2: 20
  model_params_chi2:
    n_jobs: -1
    random_state: 42
  chi2_p_value_threshold: 0.001

  # VARIANCE THRESHOLD
  variance_threshold: 0