hyperparameters:

  RandomForestClassifier:
    n_estimators: [100, 200]
    max_depth: [5, 10]
    random_state: [2021]

  XGBClassifier:
    n_estimators: [100, 200]
    max_depth: [3, 6]
    learning_rate: [0.05, 0.1]
    random_state: [2021]
    use_label_encoder: [False]
    eval_metric: ["logloss"]

  GradientBoostingClassifier:
    n_estimators: [100, 200]
    max_depth: [3, 6]
    learning_rate: [0.05, 0.1]
    random_state: [2021]

  LogisticRegression:
    penalty: ["l2"]
    C: [0.1, 1.0, 10.0]
    solver: ["liblinear"]
    max_iter: [100]

  KNeighborsClassifier:
    n_neighbors: [3, 5, 7]
    weights: ["uniform", "distance"]
    metric: ["minkowski"]

  # SVC:
  #   C: [0.1, 1.0]
  #   kernel: ["rbf", "linear"]
  #   gamma: ["scale"]
