
parameters_feature_selection:
  # RFE
  n_features_rfe: [14,16,18, 20]
  model_params_rfe:
    n_estimators: 500
    max_depth: 8
    random_state: 42
    n_jobs: -1



  # BORUTA
  model_params_boruta:
    n_estimators: 500
    max_depth: 8
    random_state: 42
    n_jobs: -1
  max_iter_boruta: 100


  # CHI2
  k_features_chi2: 20
  model_params_chi2:
    n_jobs: -1
    random_state: 42
  chi2_p_value_threshold: 0.05

  # VARIANCE THRESHOLD
  variance_threshold: 0.01